In [69]:
import numpy as np

In [70]:
A = np.array([[8, 1, 4, 2, 1],
              [8, 6, 4, 2, 1],
              [1, 2, 3, 4, 1],
              [8, 0, 6, 2, 5],
              [1, 9, 6, 4, 1]])

In [79]:
np.linalg.inv(A)

array([[ 1.33333333e-02,  1.36666667e-01,  3.33333333e-02,
        -1.66666667e-02, -1.00000000e-01],
       [-2.00000000e-01,  2.00000000e-01,  0.00000000e+00,
         2.42372632e-18,  0.00000000e+00],
       [ 4.66666667e-01, -4.66666667e-01, -3.33333333e-01,
        -8.95748122e-18,  3.33333333e-01],
       [-1.20000000e-01,  1.45000000e-01,  4.50000000e-01,
        -5.83333333e-02, -1.83333333e-01],
       [-5.33333333e-01,  2.83333333e-01,  1.66666667e-01,
         2.50000000e-01, -1.66666667e-01]])

In [81]:
np.identity(len(A))

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [82]:
np.eye(len(A))

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [89]:
def invert_matrix(matrix):
    rows, columns = matrix.shape
    
    # sprawdzenie rozmiaru macierzy    
    if rows != columns:
        raise ValueError("Macierz musi być kwadratowa.")
        
    # stworzenie macierzy jednostkowej o wymiarach macierzy 
    identity_matrix = np.identity(rows)
    
    # stworzenie kopii macierzy głównej i jednostkowej
    matrix_copy = matrix.astype(float)
    identity_matrix_copy = identity_matrix.astype(float)
    
    # pobranie długości macierzy głównej
    n = len(matrix)
    
    # uruchomienie pętli przechodzącej po długości macierzy głównej (wiersze)
    for i in range(n):
        # wyliczenie wartości po przekątnej macierzy głównej 
        value = 1 / matrix_copy[i][i]
        
        # przemnożenie aktualnego wiersza macierzy głównej i jednostkowej przez uzyskaną wartosc w konkretnej iteracji
        matrix_copy[i,:] *= value
        identity_matrix_copy[i,:] *= value
        
        # uruchomienie kolejnej pętli przechodzącąej po długości macierzy głównej(kolumny)
        for j in range(columns):
            # postawienie warunku, który będzie omijał wartości umieszczone na przekątnej(kiedy i=j wiadomo, że to indeksy przekątnej)
            if i != j:
                # przemnożenie wartości (pozyskanej w konkretnej iteracji) przez wszystkie kolumny w danym wierszu macierzy głównej jak i jednostkowej
                var = matrix_copy[j][i]
                matrix_copy[j,:] -= var * matrix_copy[i,:]
                identity_matrix_copy[j,:] -= var * identity_matrix_copy[i,:]
    # zwrócenie zmodyfikowanej macierzy jednostkowej jako macierzy odwrotnej 
    # oraz zmodyfikowanej macierzy głównej mającej formę macierzy jednostkowej    
    return identity_matrix_copy, matrix_copy

In [107]:
A_inv, main_matrix_iden = invert_matrix(A)
A_inv

array([[ 0.01333333,  0.13666667,  0.03333333, -0.01666667, -0.1       ],
       [-0.2       ,  0.2       ,  0.        ,  0.        ,  0.        ],
       [ 0.46666667, -0.46666667, -0.33333333,  0.        ,  0.33333333],
       [-0.12      ,  0.145     ,  0.45      , -0.05833333, -0.18333333],
       [-0.53333333,  0.28333333,  0.16666667,  0.25      , -0.16666667]])

In [101]:
np.linalg.inv(A)

array([[ 1.33333333e-02,  1.36666667e-01,  3.33333333e-02,
        -1.66666667e-02, -1.00000000e-01],
       [-2.00000000e-01,  2.00000000e-01,  0.00000000e+00,
         2.42372632e-18,  0.00000000e+00],
       [ 4.66666667e-01, -4.66666667e-01, -3.33333333e-01,
        -8.95748122e-18,  3.33333333e-01],
       [-1.20000000e-01,  1.45000000e-01,  4.50000000e-01,
        -5.83333333e-02, -1.83333333e-01],
       [-5.33333333e-01,  2.83333333e-01,  1.66666667e-01,
         2.50000000e-01, -1.66666667e-01]])

In [ ]:
# Macierz odwrotna do macierzy kwadratowej A (ozn. A^(-1)) to taka macierz, że
# A * A^(−𝟏) = 𝑨^(−𝟏) * A = I
# gdzie I to macierz jednostkowa takiego samego stopnia jak macierz A.

In [109]:
# sprawdzenie poprzez podstawienie do funkcji np.allclose przemnożonych
# macierzy początkowej i odwróconej i przyrównanie do otrzymanej zmodyfikowanej macierzy głównej

print(np.allclose(np.dot(A, A_inv), main_matrix_iden))

True
