In [1]:
import numpy as np

In [2]:
def det_sarrus(matrix):
#   obliczenie wyznacznika macierzy stosując tzw. metodę Sarrusa
    det = (matrix[0][0] * matrix[1][1] * matrix[2][2] +
               matrix[0][1] * matrix[1][2] * matrix[2][0] +
               matrix[0][2] * matrix[1][0] * matrix[2][1] -
               matrix[0][2] * matrix[1][1] * matrix[2][0] -
               matrix[0][1] * matrix[1][0] * matrix[2][2] -
               matrix[0][0] * matrix[1][2] * matrix[2][1])

    return det

def det(A):
    # obliczenie wyznacznika macierzy 2x2 poprzez odjęcie przemnożonycxh odpowiednich wartości na przekątnych
    if A.shape == (2,2):
        res = A[0][0] * A[1][1] - A[1][0] * A[0][1]
        return res
    
def determinant(matrix):
    if matrix.shape == (3,3):
#       obliczenie wyznacznika macierzy rozwinięciem Laplace'a względem 2 wiersza, używając pomocniczej funkcji det
        res = matrix[1][0] * (-1) ** (2+1) * det(np.array([[matrix[0][1], matrix[0][2]], [matrix[2][1], matrix[2][2]]])) + \
              matrix[1][1] * (-1) ** (2+2) * det(np.array([[matrix[0][0], matrix[0][2]], [matrix[2][0], matrix[2][2]]])) + \
              matrix[1][2] * (-1) ** (2+3) * det(np.array([[matrix[0][0], matrix[0][1]], [matrix[2][0], matrix[2][1]]]))
        
        return res
    
def transpose(matrix):
#   utworzenie macierzy wynikowej o rozmiarze odwrotnym do macierzy początkowej(kolumny na wiersze)
    C = np.zeros((len(matrix[0]),len(matrix)))
#   przejście po wierszach i kolumnach macierzy początkowej
    for i in range(len(matrix)):
        for j in range(len(matrix[0])):
            # przypisanie elementów macierzy początkowej do macierzy wynikowej w odwrotnej kolejnosci
            C[j][i] = matrix[i][j]
#   zwrócenie macierzy wynikowej       
    return C

In [26]:
def inverse_2x2(matrix):
    # obliczenie wyznacznika macierzy
    determinant = det(matrix)
    
    # sprawdzenie, czy macierz jest odwracalna, wyznacznik nie może być równy 0
    if determinant == 0:
        return "Macierz nie jest odwracalna"
    
    # utworzenie macierzy dopełnień
    complement = np.array([[matrix[1][1], -matrix[1][0]], [-matrix[0][1], matrix[0][0]]])
    
    # transpozycja macierzy dopełnień
    transposed = transpose(complement)
    
    # podzielenie macierzy dopełnień przez wyznacznik
    inverse = transposed / determinant
    
    return inverse

In [42]:
def inverse_3x3(matrix):
    # obliczenie wyznacznika macierzy
    determinant = det_sarrus(matrix)
    # sprawdzenie, czy macierz jest odwracalna, wyznacznik nie może być równy 0
    if determinant == 0:
        return "Macierz nie jest odwracalna"
    
    tmp = [[matrix[1][1] * matrix[2][2] - matrix[1][2] * matrix[2][1], matrix[0][2] * matrix[2][1] - matrix[0][1] * matrix[2][2], matrix[0][1] * matrix[1][2] - matrix[0][2] * matrix[1][1]],
           [matrix[1][2] * matrix[2][0] - matrix[1][0] * matrix[2][2], matrix[0][0] * matrix[2][2] - matrix[0][2] * matrix[2][0], matrix[0][2] * matrix[1][0] - matrix[0][0] * matrix[1][2]],
           [matrix[1][0] * matrix[2][1] - matrix[1][1] * matrix[2][0], matrix[0][1] * matrix[2][0] - matrix[0][0] * matrix[2][1], matrix[0][0] * matrix[1][1] - matrix[0][1] * matrix[1][0]]]
    
    # podzielenie macierzy przez wyznacznik
    inverse = tmp / determinant
    
    return inverse

In [41]:
def inverse(matrix):
    if matrix.shape == (2, 2):
        return inverse_2x2(matrix)
    elif matrix.shape == (3, 3):
        return inverse_3x3(matrix)
    else:
        return "Macierz powinna mieć rozmiar 2x2 lub 3x3"

In [17]:
A = np.array([[3, 6], [0, 9]])

In [6]:
inverse_2x2(A)

array([[ 0.33333333, -0.22222222],
       [ 0.        ,  0.11111111]])

In [7]:
np.linalg.inv(A)

array([[ 0.33333333, -0.22222222],
       [ 0.        ,  0.11111111]])

In [8]:
B = np.array([[2, 1], [5, 3]])

In [9]:
inverse_2x2(B)

array([[ 3., -1.],
       [-5.,  2.]])

In [10]:
np.linalg.inv(B)

array([[ 3., -1.],
       [-5.,  2.]])

In [11]:
C = np.array([[-3, -9], [1, 3]])

In [12]:
inverse_2x2(C)

'Macierz nie jest odwracalna'

In [13]:
# sprawdzenie

np.linalg.inv(C)

LinAlgError: Singular matrix

In [33]:
D = np.array([[1, 0, 5], [2, 7, 6], [8, 3, 2]])

In [34]:
inverse_3x3(D)

array([[ 0.01574803, -0.05905512,  0.13779528],
       [-0.17322835,  0.1496063 , -0.01574803],
       [ 0.19685039,  0.01181102, -0.02755906]])

In [35]:
np.linalg.inv(D)

array([[ 0.01574803, -0.05905512,  0.13779528],
       [-0.17322835,  0.1496063 , -0.01574803],
       [ 0.19685039,  0.01181102, -0.02755906]])

In [23]:
E = np.array([[3, -1, 1], [5, 1, 4], [-1, 3, 2]])

In [22]:
inverse_3x3(E)

'Macierz nie jest odwracalna'

In [29]:
inverse(A)

array([[ 0.33333333, -0.22222222],
       [ 0.        ,  0.11111111]])

In [30]:
inverse(B)

array([[ 3., -1.],
       [-5.,  2.]])

In [31]:
inverse(C)

'Macierz nie jest odwracalna'

In [36]:
inverse(D)

array([[ 0.01574803, -0.05905512,  0.13779528],
       [-0.17322835,  0.1496063 , -0.01574803],
       [ 0.19685039,  0.01181102, -0.02755906]])

In [37]:
inverse(E)

'Macierz nie jest odwracalna'

In [39]:
F = np.array([[1, 2, 3], [1, 2, 3]])

In [40]:
inverse(F)

'Macierz powinna mieć rozmiar 2x2 lub 3x3'