In [18]:
import numpy as np

## Zad 1

In [50]:
# funkcja mnożąca dwie macierze oraz zwracająca macierz iloczynów
def multiply_matrix(matrix_a, matrix_b):
#   warunek sprawdzający czy możliwe jest mnożenie macierzy,
#   poprzez porównanie liczby kolumn pierwszej oraz wierszy drugiej
    if  matrix_a.shape[1] == matrix_b.shape[0]:
#       utworzenie macierzy wynikowej 
        C = np.zeros((matrix_b.shape[1],matrix_a.shape[0]))
#       iteracja kolejno po liczbie wierszy pierwszej macierzy, liczbie kolumn drugiej
#       oraz liczbie wierszy drugiej
        for i in range(len(matrix_a)):
            for j in range(len(matrix_b[0])):
                for k in range(len(matrix_b)):
                    # przemnożenie poszczególnych elementów macierzy, dodanie w odpowiednie pozycje do macierzy zerowej
                    C[i][j] += matrix_a[i][k] * matrix_b[k][j]
        return C
    else:
#       komunikat o błędzie
        return "Macierze nie mogą być pomnożone, liczba kolumn pierwszej macierzy i liczba wierszy drugiej muszą być równe"
        

In [51]:
A = np.array([[2, 1, 1],
            [1, 3, 6],
            [4, 5, 5]]) 

B = np.array([[1, 0, 5],
            [2, 1, 6],
            [0, 3, 0]])

D = np.array([[1, 0, 5],
            [2, 1, 6],
            [0, 3, 0],
            [1, 2, 3]])

E = np.array([[1, 0, 5, 3],
            [2, 1, 6, 5],
            [0, 3, 2, 0]])


In [52]:
multiply_matrix(D, E)

array([[ 1., 15., 15.,  3.],
       [ 4., 19., 28., 11.],
       [ 6.,  3., 18., 15.],
       [ 5., 11., 23., 13.]])

In [53]:
multiply_matrix(A, B)

array([[ 4.,  4., 16.],
       [ 7., 21., 23.],
       [14., 20., 50.]])

In [54]:
# sprawdzenie 
D.dot(E)

array([[ 1, 15, 15,  3],
       [ 4, 19, 28, 11],
       [ 6,  3, 18, 15],
       [ 5, 11, 23, 13]])

In [55]:
A.dot(B)

array([[ 4,  4, 16],
       [ 7, 21, 23],
       [14, 20, 50]])

## Zad 2

In [109]:
def det_sarrus(matrix):
#   obliczenie wyznacznika macierzy stosując tzw. metodę Sarrusa
    det = (matrix[0][0] * matrix[1][1] * matrix[2][2] +
               matrix[0][1] * matrix[1][2] * matrix[2][0] +
               matrix[0][2] * matrix[1][0] * matrix[2][1] -
               matrix[0][2] * matrix[1][1] * matrix[2][0] -
               matrix[0][1] * matrix[1][0] * matrix[2][2] -
               matrix[0][0] * matrix[1][2] * matrix[2][1])

    return det

def det(A):
    # obliczenie wyznacznika macierzy 2x2 poprzez odjęcie przemnożonycxh odpowiednich wartości na przekątnych
    if A.shape == (2,2):
        res = A[0][0] * A[1][1] - A[1][0] * A[0][1]
        return res
    
def determinant(matrix):
    if matrix.shape == (3,3):
#       obliczenie wyznacznika macierzy rozwinięciem Laplace'a względem 2 wiersza, używając pomocniczej funkcji det
        res = matrix[1][0] * (-1) ** (2+1) * det(np.array([[matrix[0][1], matrix[0][2]], [matrix[2][1], matrix[2][2]]])) + \
              matrix[1][1] * (-1) ** (2+2) * det(np.array([[matrix[0][0], matrix[0][2]], [matrix[2][0], matrix[2][2]]])) + \
              matrix[1][2] * (-1) ** (2+3) * det(np.array([[matrix[0][0], matrix[0][1]], [matrix[2][0], matrix[2][1]]]))
        
        return res

In [92]:
arr = np.array([[1, 4, 5],
                [2, 1, 6],
                [0, 3, 2]])

arr2 = np.array([[6, 1, 1],
                [4, -2, 5],
                [2, 8, 7]])

arr2x2 = np.array([[2, 1],
                   [1, 0]])

In [93]:
det(arr2x2)

-1

In [126]:
determinant(arr)

-2

In [125]:
det_sarrus(arr)

-2

In [127]:
# sprawdzenie

np.linalg.det(arr)

-2.000000000000001

## Zad 3

In [119]:
def transpose(matrix):
#   utworzenie macierzy wynikowej o rozmiarze odwrotnym do macierzy początkowej(kolumny na wiersze)
    C = np.zeros((len(matrix[0]),len(matrix)))
#   przejście po wierszach i kolumnach macierzy początkowej
    for i in range(len(matrix)):
        for j in range(len(matrix[0])):
            # przypisanie elementów macierzy początkowej do macierzy wynikowej w odwrotnej kolejnosci
            C[j][i] = matrix[i][j]
#   zwrócenie macierzy wynikowej       
    return C

In [120]:
arr4 = np.array([[3, 2, 4, 1, 8, 0],
                 [2, 3, 5, 6, 0, 3],
                 [7, 7, 2, 1, 4, 5]])

In [121]:
transpose(arr4)

array([[3., 2., 7.],
       [2., 3., 7.],
       [4., 5., 2.],
       [1., 6., 1.],
       [8., 0., 4.],
       [0., 3., 5.]])

In [122]:
# sprawdzenie

np.transpose(arr4)

array([[3, 2, 7],
       [2, 3, 7],
       [4, 5, 2],
       [1, 6, 1],
       [8, 0, 4],
       [0, 3, 5]])