In [1]:
import numpy as np
import tensorflow as tf

In [3]:
# zad 1

arr = np.array([1, 4, 5, 6, 2, 1, 5, 6, 7, 0])

index = 5
arr2 = np.delete(arr, index)

new_vector = np.append(arr2, 8)

new_vector

array([1, 4, 5, 6, 2, 5, 6, 7, 0, 8])

In [4]:
for i in range(len(new_vector)):
    if i % 2 == 1:
        new_vector[i] += 2
        
new_vector

array([ 1,  6,  5,  8,  2,  7,  6,  9,  0, 10])

In [7]:
reverse = new_vector[::-1]

reverse

array([10,  0,  9,  6,  7,  2,  8,  5,  6,  1])

In [9]:
# zad2

vec = np.array([1, 2, 3, 4, 5])
scalar = 3
result = vec * scalar

li = [1, 2, 3, 4, 5]
result2 = li * scalar

print(result)
print(result2)

# mnożenie wektora przez skalar skutkuje przemnożeniem każdej wartości w wektorze 
# natomiast poprzez pomnożenie listy przez skalar otrzymamy w tym przypadku
# potrojoną liczbę elementów oraz powielenie elementów listy

[ 3  6  9 12 15]
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [10]:
# zad3

matrix = np.array([[3, 5, 0],[2, 6, 1],[3, 8, 9]])
matrix[0][0] = -1
matrix[1][1] = 44
matrix[-1][-1] = 0
matrix

array([[-1,  5,  0],
       [ 2, 44,  1],
       [ 3,  8,  0]])

In [11]:
# zad4

for i in range(len(matrix[0])):
    for j in range(len(matrix[1])):
        if i % 2 == 0 and j % 2 == 0:
            matrix[i][j] = 0
            
matrix

array([[ 0,  5,  0],
       [ 2, 44,  1],
       [ 0,  8,  0]])

In [12]:
# zad5

matrix1 = np.array([[2, 1, 1],[1, 3, 6],[4, 5, 5]])
matrix2 = np.array([[1, 0, 5],[2, 1, 6],[0, 3, 0]])

for i in range(len(matrix1[0])):
    for j in range(len(matrix1[1])):
            matrix1[i][j] += matrix2[i][j]
            
matrix1

array([[ 3,  1,  6],
       [ 3,  4, 12],
       [ 4,  8,  5]])

In [13]:
# zad6

t = tf.constant([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])

print(t)

# Tensor ten zawiera liczby całkowite od 1 do 16, o wymiarach 4x4, czyli 4 wierszach i 4 kolumnach o czym powiadamia nas shape=(4,4),
# możemy wyczytać, że typem danych jest int32, ponieważ TensorFlow domyślnie używa tego typu danych dla liczb całkowitych,
# liczby całkowite są przechowywane w formacie 32-bitowym

tf.Tensor(
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]], shape=(4, 4), dtype=int32)
